# Generated by Django 5.0 on 2023-12-31 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=256)),
                ('team_away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_away_matches', to='teams.teams')),
                ('team_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_home_matches', to='teams.teams')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedule',
            },
        ),
    ]
