# Generated by Django 5.0 on 2024-01-04 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='team_away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_away_matches', to='teams.teams'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_home_matches', to='teams.teams'),
        ),
    ]
