# Generated by Django 5.0 on 2024-01-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_name', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('year', models.FloatField()),
                ('city', models.CharField(max_length=255)),
                ('conference', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
