# Generated by Django 5.0 on 2024-01-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_alter_bet_match_alter_odds_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='money',
            field=models.FloatField(default=0.0),
        ),
    ]
